<html>
    <head>
        <title>PHP Test</title>
    </head>
    <body>
        <?php
            //Design notes: Display general guideline expamples from book under each sphere filtered by ability
            // Have buttons that let the user filter for different conditions or metatags
            //Put data from text file into array
            //test data for formatting
            // ----- call ------
        $csvdata = array (
        array("Name","Technique","Form","Level","Book","Page","Notes","Text","Requisites"),
        array("Blissful Sensations","Cr","Co","30","MoH","20","","text",""),
        array("Soothe Pains of the Beast","Cr","An","20","ArM5","117","Ritual","text",""),
        array("True Rest of the Injured Brute","Cr","An","20","ArM5","117","","text",""),
        array("Repair Cracks and Tears","Cr","An","20","Covs","99","Ritual","text",""),
        array("Piercing Lance of Bone","Cr","An","20","L&tL","60","","text",""),
        array("Sheering the Unseen Sheep","Cr","An","20","MoH","56","","text",""),
        array("Worm of the Soil","Cr","An","20","MoH","82","","text",""),
        array("Summoning the Creeping Death","Cr","An","25","HoH:S","34","","text",""),
        array("Flight Perfected","Cr","An","25","MoH","82","","text",""),
        array("Recruiting A Tiny Phalanx","Cr","Re","30","MoH","12","","text","An"),
        array("Sturdy Mantle of the Traveler","Cr","An","30","MoH","56","","text",""),
        array("Flight Divorced","Cr","An","30","MoH","82","","text",""),
        array("Strength Extinguished","Cr","An","30","MoH","82","","text",""),
        array("Weaver\’s Trap of Webs","Cr","An","35","ArM5","117","","text",""),
        array("Wizard\’s Mount","Cr","An","35","ArM5","117","","text",""),
        array("Strength Renewed","Cr","An","35","MoH","82","","text",""),
        array("Harmonic Metamorphosis of the Beast","Cr","Mu","35","MoH","83","Hermetic Metamorphosis","text","An"),
        array("Champion\'s Strength","Cr","An","40","BCoC","61","Ritual","text",""),
        array("Mend the Broken Figure","Cr","An","40","BCoC","61","Ritual","text",""),
        array("Venomous Velites","Cr","Re","40","HoH:TL","139","","text","An"),
        array("Curse of the Ravenous Swarm","Cr","Re","45","ArM5","117","Ritual","text","An"),
        array("Twinning the Tome","Cr","In","50","HoH:TL","101","Ritual Mutantum","text","An Te"),
        array("Footsteps of Slippery Oil","Cr","Aq","5","ArM5","121","","text",""),
        array("Dagger of Ice","Cr","Re","10","HoH:S","35","","text","Aq"),
        array("Creeping Oil","Cr","Aq","15","ArM5","121","","text",""),
        array("Mighty Torrent of Water","Cr","Aq","20","ArM5","121","","text",""),
        array("Alchemist\'s Revenge","Cr","Aq","25","HoH:S","35","","text",""),
        array("Rarefy the Crude Water","Cr","Aq","30","RoP:M","133","Ritual","text",""),
        array("Deluge of Rushing and Dashing","Cr","Aq","40","ArM5","121","","text",""),
        array("Adoration of the Magic Isle","Cr","Aq","50","RoP:M","27","Ritual Magic Realm Magic","text",""),
        array("Air\’s Ghostly Form","Cr","Au","5","ArM5","125","","text",""),
        array("Chamber of Spring Breezes","Cr","Au","5","ArM5","125","","text",""),
        array("Jupiter\’s Resounding Blow","Cr","Au","10","ArM5","125","","text",""),
        array("Stench of the Twenty Corpses","Cr","Au","10","ArM5","125","","text",""),
        array("Wreaths of Foul Smoke","Cr","Au","10","ArM5","125","","text",""),
        array("Chamber of Summer Breezes","Cr","Au","10","Covs","100","","text","Ig"),
        array("Broom of the Winds","Cr","Au","15","ArM5","125","","text",""),
        array("Charge of the Angry Winds","Cr","Au","15","ArM5","125","","text",""),
        array("Bridge of Gnomes","Cr","Au","15","MoH","122","","text",""),
        array("Circling Winds of Protection","Cr","Re","20","ArM5","125","","text","Au"),
        array("Clouds of Rain and Thunder","Cr","Au","25","ArM5","126","","text",""),
        array("Clouds of Summer Snow","Cr","Au","25","ArM5","126","","text",""),
        array("Pull of the Skybound Winds","Cr","Au","30","ArM5","126","","text",""),
        array("Wings of the Soaring Wind","Cr","Re","30","ArM5","126","","text","Au"),
        array("Catapult of the Mighty Winds","Cr","Re","30","HoH:S","35","","text","Au"),
        array("Clouds of Obscuring Sand","Cr","Au","30","MoH","12","","text",""),
        array("Incantation of Lightning The","Cr","Au","35","ArM5","126","","text",""),
        array("Breath of the Open Sky","Cr","Au","40","ArM5","126","Ritual","text",""),
        array("Wrath of Whirling Winds and Water","Cr","Au","65","ArM5","126","Ritual","text",""),
        array("Bind Wound","Cr","Co","10","ArM5","129","","text",""),
        array("Charm Against Putrefaction","Cr","Co","10","ArM5","129","","text",""),
        array("Chirurgeon\’s Healing Touch The","Cr","Co","20","ArM5","129","Ritual","text",""),
        array("Gentle Touch of the Purified Body","Cr","Co","20","ArM5","129","Ritual","text",""),
        array("Purification of the Festering Wounds","Cr","Co","20","ArM5","129","","text",""),
        array("Ward the Cruel Touch of Pestilence","Cr","Co","20","HoH:S","100","","text",""),
        array("Widening the River Styx","Cr","Co","20","MoH","20","Ritual","text",""),
        array("Touch of the Blessed Virgin","Cr","Co","20","MoH","28","","text",""),
        array("Restoration of the Defiled Body","Cr","Co","25","ArM5","129","Ritual","text",""),
        array("Severed Limb Made Whole The","Cr","Co","25","ArM5","129","Ritual","text",""),
        array("Cheating the Reaper","Cr","Co","30","ArM5","129","Ritual","text",""),
        array("Replenishing the Fount of the Magus","Cr","Co","30","GotF","39","Path of Energy","text",""),
        array("Gentle Caress of Aesclepius","Cr","Co","30","HoH:S","100","","text",""),
        array("A Limb Bereft","Cr","Re","30","MoH","83","","text","Co"),
        array("(Physical Characteristic) of the Followers","Cr","Co","35","HoH:TL","103","Ritual","text",""),
        array("Incantation of the Body Made Whole","Cr","Co","40","ArM5","129","Ritual","text",""),
        array("Artemis\' Fertility","Cr","Co","40","MoH","20","","text",""),
        array("Bestow the Blessing of Apollon","Cr","Co","50","MoH","21","Ritual","text",""),
        array("Incantation of the Warriors Made Whole","Cr","Co","50","MoH","21","Ritual","text",""),
        array("Saoshant\'s Elixer","Cr","Co","50","RoP:D","117","Ritual Holy Magic","text",""),
        array("(Physical Characteristic) of the Heroes","Cr","Co","60","HoH:TL","103","Ritual","text",""),
        array("Blessing of Artemis\' Fertility","Cr","Co","65","MoH","21","Ritual","text",""),
        array("Shadow of Life Renewed The","Cr","Co","75","ArM5","129","Ritual","text","Me"),
        array("Circle of Eternal Spring","Cr","He","4","MoH","38","","text",""),
        array("Grow the Bountiful Feast","Cr","He","4","MoH","75","","text",""),
        array("Conjure the Sturdy Vine","Cr","He","5","ArM5","135","","text",""),
        array("The Magic Flute","Cr","He","5","MoH","139","","text",""),
        array("Statim Sessio","Cr","He","10","MoH","30","","text",""),
        array("Clothe the Naked Form","Cr","He","10","MoH","58","","text",""),
        array("Trap of the Entwining Vines","Cr","He","15","ArM5","135","","text",""),
        array("Ladder of Ivy","Cr","He","15","MoH","38","","text",""),
        array("Conjuration of Wild Thyme","Cr","He","20","A&A","66","","text",""),
        array("Muiniature of Immortality The","Cr","He","20","A&A","133","","text","AnTe"),
        array("Bridge of Wood","Cr","He","20","ArM5","135","","text",""),
        array("Wall of Thorns","Cr","He","20","ArM5","135","","text",""),
        array("Sprouting Out of Season","Cr","He","20","Covs","79","","text",""),
        array("Apple That Etches The","Cr","He","20","Covs","96","Ritual","text",""),
        array("The Traveler\'s Fortress of Cloth","Cr","He","20","MoH","58","","text",""),
        array("Weaver\'s Trap of Threads","Cr","He","20","MoH","58","","text",""),
        array("Plant the Bountiful feast","Cr","He","20","MoH","75","Ritual","text",""),
        array("Heal Thy Broken Voice","Cr","He","20","MoH","139","","text",""),
        array("Wall of Living Wood","Cr","He","25","ArM5","135","","text",""),
        array("Fast Grow","Cr","He","30","MoH","39","","text",""),
        array("Bountiful Feast The","Cr","He","35","ArM5","135","Ritual","text",""),
        array("Conjuration of Bread","Cr","He","35","LoM","116","Ritual","text",""),
        array("Fortress of Oak","Cr","Mu","40","MoH","39","Ritual","text","He Te"),
        array("Moonbeam","Cr","Ig","3","ArM5","139","","text",""),
        array("Palm of Flame","Cr","Ig","5","ArM5","139","","text",""),
        array("Evening\'s Comfort","Cr","Ig","5","MoH","30","","text",""),
        array("Palm of  Odorous Flame","Cr","Ig","5","MoH","30","","text",""),
        array("Repel Winter\'s Clutches","Cr","Ig","5","MoH","75","","text",""),
        array("Coat of Prometheus","Cr","Ig","5","MoH","110","","text",""),
        array("Heat of the Searing Forge","Cr","Ig","10","ArM5","140","","text",""),
        array("Lamp Without Flame","Cr","Ig","10","ArM5","140","","text",""),
        array("Warmth of the Wood","Cr","Ig","10","MoH","40","","text",""),
        array("Blade of the Virulent Flame","Cr","Ig","15","ArM5","140","","text",""),
        array("Flash of the Scarlet Flames","Cr","Ig","15","ArM5","140","","text",""),
        array("Ignite the Inflammable Item","Cr","Ig","15","BCoC","66","","text",""),
        array("Welcome Addition of Sunlight The","Cr","Ig","15","Covs","96","","text",""),
        array("Test of the Flames","Cr","Ig","15","HoH:S","36","","text",""),
        array("Mien of Helios","Cr","Ig","15","MoH","110","","text",""),
        array("Pilum of Fire","Cr","Ig","20","ArM5","140","","text",""),
        array("Fasting Hearth","Cr","Ig","20","MoH","110","","text",""),
        array("Arc of Fiery Ribbons","Cr","Ig","25","ArM5","140","","text",""),
        array("Coat of Flame","Cr","Re","25","ArM5","140","","text","Ig"),
        array("Brilliance of the Eagles Plummage","Cr","Ig","30","HoH:MC","29","Sensory Magic","text",""),
        array("Self Immolation","Cr","Ig","30","MoH","111","","text",""),
        array("Ball of Abysmal Flame","Cr","Ig","35","ArM5","140","","text",""),
        array("Circle of Encompassing Flames","Cr","Ig","35","ArM5","140","","text",""),
        array("Stockade of Infernos","Cr","Ig","40","MoH","111","","text",""),
        array("Conflagrative Servant","Cr","Re","45","MoH","111","","text","Ig"),
        array("Conflagration of Light","Cr","Ig","50","BCoC","66","","text",""),
        array("Dive of the Dying Phoenix","Cr","Ig","50","BCoC","66","","text",""),
        array("Last Flight of the Phoenix","Cr","Ig","50","HoH:S","37","","text",""),
        array("False Window","Cr","Im","5","HoH:S","68","","text",""),
        array("Trigger the Distant Power","Cr","Im","5","MoH","91","","text",""),
        array("Smoke of Escaping","Cr","Im","5","MoH","124","","text",""),
        array("Phantasm of the Talking Head","Cr","Im","10","ArM5","144","","text",""),
        array("Fooling the Eye","Cr","Im","10","HoH:S","68","","text",""),
        array("Silent Shout","Cr","Im","10","HoH:S","68","","text",""),
        array("An Enemy Awash in the Pure Sigil of the Magus","Cr","Im","15","HoH:S","68","","text",""),
        array("Phantasmal Troupe","Cr","Im","15","MoH","22","","text",""),
        array("Book of Images","Cr","Im","15","MoH","124","","text",""),
        array("Phantasmal Animal","Cr","Im","20","ArM5","144","","text",""),
        array("Phantasmal Fire","Cr","Im","20","ArM5","144","","text","Ig"),
        array("Veneficus Enigma","Cr","Im","20","MoH","30","","text",""),
        array("Told Story","Cr","Im","20","MoH","124","Performance Magic","text",""),
        array("Locus of the Literatus","Cr","Im","20","RoP:M","27","Ritual Magic Realm Magic","text",""),
        array("Phantasm of the Human Form","Cr","Im","25","ArM5","144","","text",""),
        array("First Furrow Guides the Second The","Cr","In","25","Covs","97","","text","Im"),
        array("Raise the Veronese Flag","Cr","Im","30","LoM","116","","text",""),
        array("Cage of Bronze","Cr","Im","30","MoH","124","Glamour Magic","text",""),
        array("Phantasmal Horse","Cr","Im","30","MoH","124","Glamour Magic","text",""),
        array("Oneiropomp\'s Treasure The","Cr","Im","30","TMRE","109","Ritual Greater Dream Grimore","text",""),
        array("Haunt of the Living Ghost","Cr","In","35","ArM5","144","","text","Im"),
        array("Eternal Repitition in a Bottomless Pool","Cr","Im","35","Covs","101","","text",""),
        array("Story of Legend","Cr","Im","35","MoH","124","Performance Magic","text",""),
        array("Shadow of Human Life The","Cr","Im","40","ArM5","144","","text","Me"),
        array("To Mark With Umbrage","Cr","Im","40","HoH:TL","139","","text",""),
        array("Doppelganger","Cr","Im","40","MoH","124","Glamour Magic","text","Me"),
        array("Image of the Lady","Cr","Im","40","MoH","124","Glamour Magic","text","Me"),
        array("Garden of Eden","Cr","Im","45","MoH","125","Glamour Magic","text",""),
        array("By His Work","Cr","Me","5","HoH:TL","73","","text",""),
        array("Words of the Unbroken Silence","Cr","Me","10","ArM5","148","","text",""),
        array("Agnosia","Cr","Me","10","HoH:S","69","","text",""),
        array("Look at Me","Cr","Me","15","A&A","32","","text",""),
        array("Panic of the Trembling Heart","Cr","Me","15","ArM5","148","","text",""),
        array("Rising Ire","Cr","Me","15","ArM5","148","","text",""),
        array("Rising Passion","Cr","Me","15","GotF","73","","text",""),
        array("Heart of the Lion","Cr","Me","15","HoH:S","37","","text",""),
        array("Catching the Eye","Cr","Me","15","MoH","92","","text",""),
        array("Welcome Stranger The","Cr","Me","15","MoH","140","","text",""),
        array("A Moment\'s Reflecetion","Cr","Me","20","A&A","35","","text",""),
        array("Memory of the Distant Dream","Cr","Me","20","ArM5","148","","text",""),
        array("Pains of the Perpetual Worry","Cr","Me","20","ArM5","148","","text",""),
        array("Gossip of the Marketplace","Cr","Re","20","GotF","73","","text","Me"),
        array("Scent of the Predator","Cr","Me","20","HoH:MC","29","Sensory Magic","text",""),
        array("Creation of the Simple","Cr","Me","20","HoH:S","69","","text",""),
        array("Creation of an Undeserved Reputation","Cr","Me","20","HoH:S","70","","text",""),
        array("The Far Speaking Voice","Cr","Me","20","HoH:S","97","","text",""),
        array("Orpheus\' Ballad","Cr","Me","20","MoH","140","","text",""),
        array("Enhance the Memory Palace","Cr","Me","20","TMRE","26","","text",""),
        array("Constructing the Memory Palace","Cr","Me","20","TMRE","27","","text",""),
        array("Human Figment of the Wandering Mind","Cr","Me","25","A&A","32","","text",""),
        array("The Ob of Mot","Cr","Me","25","AncMag","32","Canaanite Necromancy","text",""),
        array("Weight of a Thousand Hells","Cr","Me","25","ArM5","148","","text",""),
        array("My New Best Friend","Cr","Me","25","GotF","72","","text",""),
        array("Good Witness The","Cr","Me","25","HoH:TL","73","","text",""),
        array("Robed in Angelic Beauty","Cr","Me","25","MoH","30","","text","Im"),
        array("To Sing of Good Meat and Drink","Cr","Me","25","MoH","141","","text",""),
        array("Memory Palace of the Sage","Cr","Me","25","TMRE","27","Ritual","text",""),
        array("Unwelcoming Room The","Cr","Me","30","MoH","101","Hermetic Geometry","text",""),
        array("Gift of Reason","Cr","Me","35","ArM5","148","Ritual","text",""),
        array("(Mental Characteristic) of the Followers","Cr","Me","35","HoH:TL","103","Ritual","text",""),
        array("The Irresistable Press Gang","Cr","Me","35","L&tL","84","","text",""),
        array("Missive of Memory","Cr","Me","40","MoH","65","","text",""),
        array("Instant Loyalty of the Rebellious Turb","Cr","Me","50","Covs","41","","text",""),
        array("(Mental Characteristic) of the Heroes","Cr","Me","60","HoH:TL","103","Ritual","text",""),
        array("Bind the Living Ghost","Cr","Pe","31","TMRE","71","Ritual Living Ghost","text","Re Me Co"),
        array("Seal the Earth","Cr","Te","15","ArM5","152","","text",""),
        array("Sword from the Unseen Scabbard","Cr","Te","15","HoH:S","37","","text",""),
        array("Touch of Midas","Cr","Te","20","ArM5","153","Ritual","text",""),
        array("Seal the Breach","Cr","Te","20","LoM","116","Ritual","text",""),
        array("Substance Over Form","Cr","Mu","20","TMRE","108","Greater Dream Grimore","text","Te Me"),
        array("Wall of Protecting Stone","Cr","Te","25","ArM5","153","","text",""),
        array("Form the Hermetic Boundary","Cr","Te","25","MoH","75","","text",""),
        array("Silvery Scales of the Knight","Cr","Te","30","HoH:S","37","","text","An"),
        array("Conjuring the Mystic Tower","Cr","Te","35","ArM5","153","Ritual","text",""),
        array("The Riches That Are Rightfully Mine(d)","Cr","Te","35","Covs","61","","text",""),
        array("A Simple Method for Rapid Vallation","Cr","Te","35","HoH:TL","141","","text",""),
        array("Craft the Mechanism","Cr","In","35","TMRE","52","Ritual","text","Te"),
        array("Duplicate the Mechanism","Cr","In","35","TMRE","52","Ritual","text","Te"),
        array("Laboratory of Bonisagus The","Cr","Te","45","Covs","122","Ritual","text",""),
        array("Conjuring the House of God","Cr","Te","45","A&A","133","Ritual","text",""),
        array("Phantom Gift The","Cr","Vi","15","ArM5","157","","text",""),
        array("Kiss of the Enigma","Cr","Vi","15","MoH","83","","text",""),
        array("Plucking the Hair From the Billy Goat\'s Chin","Cr","Vi","20","RoP:TI","121","","text",""),
        array("Mercury\'s Blessing","Cr","Vi","25","HoH:TL","103","Ritual","text",""),
        array("Enigma\’s Gift The","Cr","Vi","30","ArM5","157","","text",""),
        array("Neriusian Portal","Cr","Vi","65","RoP:D","94","Ritual Holy Magic","text",""),
        array("Shell of False Determinations","Cr","Vi","0","ArM5","157","Ritual","text",""),
        array("Shell of Opaque Mysteries","Cr","Vi","0","ArM5","157","Ritual","text",""),
        array("Faerie Chains of the Familiar Slave","Cr","Vi","0","HoH:MC","90","Faerie Magic","text",""),
        array("Restore the Faded Threads","Cr","Vi","0","HoH:TL","74","","text",""),
        array("(Immortal)\'s Blessing","Cr","Vi","0","RoP:D","117","Holy Magic","text",""),
        array("Feeding the Font of the Covenant","Cr","Vi","0","RoP:M","14","Ritual","text",""),
        array("Stratifying the Subtile Realities","Cr","Vi","0","RoP:M","14","Ritual","text",""),
        array("Fanning the Infernal Flames","Cr","Vi","0","RoP:TI","121","","text",""),
        array("Transformation of the Ascendant Heirarch","Cr","Vi","0","TMRE","84","Ritual Ascending to the Hall of Heroes","text",""),
        array("Image of the Beast","In","An","5","ArM5","117","","text",""),
        array("Shiver of the Lycanthrope","In","An","10","ArM5","118","","text",""),
        array("A Simple Test For the Completeness of Books","In","An","15","Covs","100","","text","He"),
        array("Numbering the Flock","In","An","20","TMRE","93","","text",""),
        array("Opening the Tome of the Animal\’s Mind","In","An","25","ArM5","118","","text",""),
        array("Books That Scream in Pain","In","An","25","Covs","100","","text","He"),
        array("Determine the Location of the Absent Volume","In","An","25","Covs","100","","text","Im"),
        array("Hunter\’s Sense","In","An","30","ArM5","118","","text",""),
        array("Determine the Location of the Absent Volume","In","Cr","30","Covs","100","","text","An Im"),
        array("To See as Others See","In","Re","45","HoH:TL","139","","text","An"),
        array("Clear Sight of the Naiad","In","Aq","5","ArM5","122","","text",""),
        array("Subtle Taste of Poison and Purity","In","Aq","5","ArM5","122","","text",""),
        array("Touch of the Pearls","In","Aq","5","ArM5","122","","text",""),
        array("Test of Fastness and Fading","In","Aq","5","Covs","96","","text",""),
        array("Call of the Rushing Waters","In","Aq","15","ArM5","122","","text",""),
        array("Voice of the Lake","In","Aq","25","ArM5","122","","text",""),
        array("Sense the Tide\'s Boundaries","In","Aq","25","MoH","75","","text",""),
        array("Enchantment of the Scrying Pool","In","Aq","30","ArM5","122","Ritual","text","Im"),
        array("True Sight of the Air","In","Au","15","ArM5","127","","text",""),
        array("Whispering Winds","In","Au","15","ArM5","127","","text",""),
        array("Sailor\’s Foretaste of the Morrow","In","Au","20","ArM5","127","","text",""),
        array("See the Paths Through the Void","In","Au","20","RoP:M","27","Magic Realm Magic","text",""),
        array("Eyes of the Bat","In","Au","25","ArM5","127","","text",""),
        array("Midwife\'s Eye","In","Co","5","AncMag","56","Fertility Magic","text",""),
        array("Physician\’s Eye","In","Co","5","ArM5","130","","text",""),
        array("Pose Clotho\'s Question","In","Co","5","MoH","21","","text",""),
        array("Revealed Flaws of Mortal Flesh","In","Co","10","ArM5","130","","text",""),
        array("Parental Inquisitiveness","In","Co","10","MoH","21","","text",""),
        array("Pose Nona\'s Question","In","Co","10","MoH","21","","text",""),
        array("Evaluate the Facing Opponent","In","Co","10","MoH","131","","text",""),
        array("Significance of the Group The","In","Co","10","TMRE","93","","text",""),
        array("The Genethlialogical Investigation","In","Co","15","A&A","72","","text",""),
        array("Whispers Through the Black Gate","In","Co","15","ArM5","130","","text","Me"),
        array("The Maculate Noblewoman","In","Co","15","MoH","21","","text",""),
        array("Verifying the Presence of Artemis\' Blessing","In","Co","15","MoH","22","","text",""),
        array("Numbering the Host","In","Co","15","TMRE","93","","text",""),
        array("Inexorable Search The","In","Co","20","ArM5","131","","text",""),
        array("The Whole From the Part","In","Co","20","HoH:TL","72","","text",""),
        array("Pull of Blood","In","Co","20","MoH","65","Faerie Magic","text",""),
        array("Sight of the Molting Magus","In","Co","25","HoH:TL","72","","text",""),
        array("Draw on Diana\'s Hounds","In","Co","30","AncMag","45","Ritual Defixio Magic","text",""),
        array("Eye of the Sage The","In","Co","30","ArM5","131","","text","Im"),
        array("Sight of the True Form","In","Co","0","ArM5","130","","text",""),
        array("Probe Nature\’s Hidden Lore","In","He","4","ArM5","136","","text",""),
        array("Hunt for the Wild Herb","In","He","5","ArM5","136","","text",""),
        array("Intuition of the Forest","In","He","10","ArM5","136","","text",""),
        array("Shriek of the Impending Shafts","In","He","15","ArM5","136","","text",""),
        array("Carpenter\'s Keen Eye The","In","He","15","Covs","51","","text",""),
        array("Converse with Plant and Tree","In","He","25","ArM5","136","","text",""),
        array("Comprehending the Mystc Doorway","In","He","30","RoP:M","27","Magic Realm Magic","text",""),
        array("Tales of the Ashes","In","Ig","5","ArM5","141","","text",""),
        array("Shadows of the Fires Past","In","Ig","15","ArM5","141","","text",""),
        array("Vision of Heat\’s Light","In","Ig","20","ArM5","141","","text",""),
        array("Eyes of the Flame","In","Ig","35","ArM5","141","","text",""),
        array("Words of the Flickering Flame","In","Ig","35","ArM5","141","","text",""),
        array("Prying Eyes","In","Im","5","ArM5","144","","text",""),
        array("Spy the Approaching Grog","In","Im","5","MoH","30","","text",""),
        array("Traveler\'s  Foresight","In","Im","5","MoH","125","Faerie Magic","text",""),
        array("The Brushstrokes Revealed","In","Im","10","HoH:S","65","","text",""),
        array("Hearing the Silent Chorus","In","Im","15","A&A","16","","text",""),
        array("Discern Own Illusions","In","Im","15","ArM5","145","","text",""),
        array("An Ear for Distant Bells","In","Im","15","L&tL","15","","text",""),
        array("Ear for Distant Voices The","In","Im","20","ArM5","145","","text",""),
        array("Eyes of the Eagle","In","Im","25","ArM5","145","","text",""),
        array("Summoning the Distant Image","In","Im","25","ArM5","145","","text",""),
        array("To See as Through a Plethron Distant","In","Im","25","MoH","101","","text",""),
        array("Sight of the Blossom Ears of the Oak","In","Im","30","MoH","40","","text",""),
        array("Discern the Images of Truth and Falsehood","In","Im","0","ArM5","144","","text",""),
        array("Discerning Eye The","In","Im","0","HoH:TL","72","","text",""),
        array("Sight of the Transparent Motive","In","Me","10","ArM5","148","","text",""),
        array("Perception of the Conflicting Motives","In","Me","15","ArM5","149","","text",""),
        array("Anat\'s Search in the Miry abyss","In","Me","20","AncMag","32","Canaanite Necromancy","text",""),
        array("Frosty Breath of the Spoken Lie","In","Me","20","ArM5","149","","text",""),
        array("Posing the Silent Question","In","Me","20","ArM5","149","","text",""),
        array("Perceive the Eyes of Knives","In","Me","20","GotF","21","","text",""),
        array("Reveal the Lingering Spirit","In","Me","20","HoH:TL","14","","text",""),
        array("The Factor\'s Role Call","In","Me","20","MoH","92","","text",""),
        array("Thoughts Within Babble","In","Me","25","ArM5","149","","text",""),
        array("Borrow the Eyes of Another","In","Me","30","A&A","33","","text",""),
        array("See the Spirits of the Night","In","Me","30","AncMag","50","","text",""),
        array("Peering into the Mortal Mind","In","Me","30","ArM5","149","","text",""),
        array("Betraying Whispers of the Jealous Mind","In","Me","30","HoH:S","98","","text",""),
        array("Ear of Truth","In","Me","30","HoH:TL","73","","text",""),
        array("Thoughts Within Speech","In","Me","30","MoH","30","","text",""),
        array("Tread of Fellow Travelers","In","Me","30","MoH","66","Faerie Magic","text",""),
        array("Familial Secrets","In","Me","30","MoH","66","Faerie Magic","text",""),
        array("Scent of Loose Purses","In","Me","30","MoH","66","","text",""),
        array("Stench of Hate","In","Me","30","MoH","66","","text",""),
        array("Oath Breaker\'s Confession","In","Me","35","MoH","67","Faerie Magic","text",""),
        array("Opinions of the Masses","In","Me","35","MoH","67","","text",""),
        array("Probe for Pure Silver","In","Te","4","ArM5","153","","text",""),
        array("Eyes of the Eons","In","Te","10","ArM5","153","","text",""),
        array("Eyes of the Treacherous Terrain","In","Te","15","ArM5","153","","text",""),
        array("Sense the True Path","In","Te","15","HoH:TL","102","Mutantum","text",""),
        array("Miner\’s Keen Eye The","In","Te","20","ArM5","153","","text",""),
        array("Tracks of the Faerie Glow","In","Te","25","ArM5","153","","text",""),
        array("Wiadom of Sleep the","In","Te","25","MoH","141","","text","Vi"),
        array("Stone Tell of the Mind that Sits","In","Te","30","ArM5","153","","text",""),
        array("Sense the Feet that Tread the Earth","In","Te","30","ArM5","154","","text",""),
        array("Love\'s Unfaithful Witness","In","Te","35","HoH:TL","141","","text",""),
        array("Tell of the Forged","In","Te","45","HoH:TL","74","","text",""),
        array("Dream of the Artifice","In","Te","50","HoH:TL","74","","text",""),
        array("Dream of the Mind That Sits","In","Cr","50","HoH:TL","74","","text","Te"),
        array("Dream of the Forged","In","Cr","60","HoH:TL","74","Ritual","text","Te"),
        array("Sense of Magical Power","In","Vi","2","ArM5","157","","text",""),
        array("Scales of the Magical Weight","In","Vi","5","ArM5","158","","text",""),
        array("Sense the Nature of Vis","In","Vi","5","ArM5","158","","text",""),
        array("Sense the Weight of Divine Power","In","Vi","5","MoH","102","Hermetic Numerology","text",""),
        array("Sense the Hour","In","Vi","10","TMRE","51","","text",""),
        array("Bitter Taste of Betrayal","In","Vi","15","HoH:TL","75","","text",""),
        array("Piercing the Faerie Veil","In","Vi","20","ArM5","158","","text",""),
        array("Sight of the Astrological Hour","In","Vi","20","TMRE","51","","text",""),
        array("A Comparison of the Positions of the Fixed Stars","In","Vi","25","AncMag","91","Celestial Magic","text",""),
        array("Reveal the Magical Deception","In","Vi","25","GotF","21","","text",""),
        array("A Song for All These Faerie Places","In","Cr","25","MoH","142","","text","Vi Im"),
        array("A Song for All These Infernal Places","In","Cr","25","MoH","142","","text","Vi Im"),
        array("A Song for All These Magical Places","In","Cr","25","MoH","142","","text","Vi Im"),
        array("Sense of the Lingering Magic","In","Vi","30","ArM5","158","","text",""),
        array("Reveal the Lurking Watchers","In","Vi","30","HoH:S","99","","text",""),
        array("Impression of the Faded Sigil","In","Vi","30","HoH:TL","75","","text",""),
        array("Odor of the Lingering Magic","In","Vi","30","HoH:TL","75","","text",""),
        array("Sulfurous Whispers","In","Vi","30","RoP:TI","121","","text",""),
        array("Divine Heaven\'s Aspect","In","Vi","30","TMRE","51","","text",""),
        array("Sight of the Active Magics","In","Vi","40","ArM5","159","","text",""),
        array("Sight of the Sigil","In","Vi","50","HoH:TL","75","","text",""),
        array("Invisible Eye Revealed The","In","Vi","Gen","ArM5","157","","text",""),
        array("Music of the Unwanted Attention","In ","Me","25","MoH","92","","text",""),
        array("Funding the Blackmailer\'s Purse","In ","Me","30","MoH","92","","text",""),
        array("Beast of Outlandish Size","Mu","An","15","ArM5","118","","text",""),
        array("Doublet of Impenetrable Silk","Mu","An","15","ArM5","118","","text",""),
        array("Growth of the Creeping Things","Mu","An","15","ArM5","118","","text",""),
        array("Gift of Man\'s Fortitude","Mu","An","15","BCoC","61","","text",""),
        array("Plunder of Twenty Geese The","Mu","An","15","Covs","96","","text",""),
        array("The Voice of the Bjornaer Magus","Mu","An","15","HoH:MC","36","","text",""),
        array("Doublet of Silk that\'s Impenetrable","Mu","An","15","MoH","28","","text",""),
        array("Transform the Tailor\'s Craft","Mu","An","15","MoH","91","","text",""),
        array("Beast of Miniscule Proportions","Mu","An","20","ArM5","119","","text",""),
        array("Plunder of Twenty Geese The","Mu","Re","20","Covs","96","","text","An"),
        array("Fatal Register","Mu","Re","20","Covs","100","","text","An In"),
        array("Form of the (Temperament) Heartbeast ","Mu","An","20","HoH:MC","36","","text",""),
        array("Madder Woad and Weld","Mu","An","20","MoH","56","","text","He"),
        array("Touch of the Wild","Mu","An","20","MoH","82","","text",""),
        array("Beast Remade The","Mu","An","25","ArM5","119","","text","Co"),
        array("Transformation of the Ravenous Beast to the Torpid Toad","Mu","An","25","ArM5","119","","text",""),
        array("Pests of a Colossal Size","Mu","An","30","MoH","28","","text",""),
        array("Steed of Vengeance","Mu","An","35","ArM5","119","","text",""),
        array("Transformed Folio The","Mu","An","35","HoH:TL","102","Ritual Mutantum","text",""),
        array("Cloak of Nessus ","Mu","An","35","MoH","56","","text",""),
        array("The Griffin Reborn","Mu","An","35","MoH","83","","text",""),
        array("Scales of the Scorpions","Mu","An","40","MoH","12","","text",""),
        array("Icarus\'s Folly","Mu","An","40","MoH","83","","text",""),
        array("Reveal the Hidden Words","Mu","Aq","5","HoH:S","98","","text",""),
        array("Incantation of Putrid Wine","Mu","Aq","15","ArM5","122","","text",""),
        array("Lungs of the Fish","Mu","Aq","20","ArM5","122","","text","Au"),
        array("Sculpt the Living Water","Mu","Aq","20","GotF","96","","text",""),
        array("Bag of Teeth","Mu","Aq","20","MoH","12","","text","An"),
        array("Neptune\'s Imprisoning Arms","Mu","Aq","25","GotF","96","","text",""),
        array("Vile Water of Sterility","Mu","Aq","45","ArM5","122","Ritual","text",""),
        array("Appease the Queen of Winter","Mu","Aq","60","GotF","96","Ritual","text",""),
        array("Rain of Stones","Mu","Au","20","ArM5","127","","text","Te"),
        array("Talons of the Winds","Mu","Re","20","ArM5","127","","text","Au"),
        array("Curse of the Evil Humors","Mu","Au","25","HoH:S","36","","text",""),
        array("Rainbow Bridge","Mu","Au","30","MoH","122","","text",""),
        array("Infernal Smoke of Death","Mu","Au","40","ArM5","127","","text",""),
        array("Conjure from Mist","Mu","Au","40","MoH","28","","text","Te"),
        array("Fog of Confusion","Mu","Re","45","ArM5","128","Ritual","","Au Im"),
        array("Rain of Oil","Mu","Au","50","ArM5","128","Ritual","text","Aq"),
        array("Track by Scent","Mu","Co","4","MoH","131","","text","An"),
        array("Eyes of the Cat","Mu","Co","5","ArM5","131","","text","An"),
        array("The Succubus\'s Trick","Mu","Co","5","HoH:S","97","","text",""),
        array("Bushy Tail of the Branch-Dancer","Mu","Co","5","MoH","84","","text","An"),
        array("Slime of the Muck-Dweller","Mu","Co","5","MoH","84","","text","An"),
        array("Sure-Footedness of the Crag-Leaper","Mu","Co","5","MoH","84","","text","An"),
        array("Webbed Toes of the Pond-Dweller","Mu","Co","5","MoH","84","","text","An"),
        array("Slipperyness of the Eel","Mu","Co","5","SemE","35","","text","An"),
        array("Stickyness of the Lizard\'s Toes","Mu","Co","5","SemE","35","","text","An"),
        array("Assume the Stature of the Giants of Eld","Mu","Co","10","MoH","49","","text",""),
        array("Avalanche of Flesh and Steel","Mu","Co","10","MoH","49","","text",""),
        array("Disguise of the New Visage","Mu","Co","15","ArM5","131","","text",""),
        array("Preternatural Growth and Shrinking","Mu","Co","15","ArM5","131","","text",""),
        array("Ease the Suffering of Childbirth","Mu","Co","15","MoH","22","","text",""),
        array("Eyes from the Wizard Torn","Mu","In","15","MoH","83","","text","Re Co Im"),
        array("Arm of the Infant","Mu","Co","20","ArM5","131","","text",""),
        array("The Twisted Tounge","Mu","Pe","20","L&tL","84","","text","Co"),
        array("Eyes of the Housecats","Mu","Co","20","MoH","12","","text","An"),
        array("The Guardian of the Tombs","Mu","Co","20","MoH","13","","text","An"),
        array("Spirit of the Bull of Minos","Mu","Co","20","MoH","83","Ritual","text","An"),
        array("High Tree or Small Boulder","Mu","Co","20","MoH","122","","text",""),
        array("Shape of the Leafy Herbavore","Mu","Co","20","ToME","12","","text","An"),
        array("Gift of the Bear\’s Fortitude","Mu","Co","25","ArM5","131","","text",""),
        array("Shape of the Woodland Prowler","Mu","Co","25","ArM5","131","","text","An"),
        array("The Desert Wanderer","Mu","Co","25","MoH","13","","text","An"),
        array("The Blessing of Starkad","Mu","Co","25","MoH","49","","text",""),
        array("Turb of Giants","Mu","Co","25","MoH","49","","text",""),
        array("Cloak of Black Feathers","Mu","Co","30","ArM5","131","","text","An"),
        array("Curse of Circe","Mu","Co","30","ArM5","131","","text","An"),
        array("The Shadow on the Sand","Mu","Co","30","MoH","13","","text","An"),
        array("Gift of the Minotaur","Mu","Co","30","MoH","84","","text","An"),
        array("Coat of the Slippery Warrior","Mu","Co","30","ToME","12","","text","An"),
        array("The Frozen Womb","Mu","Co","35","AncMag","56","Ritual Fertility Magic","text",""),
        array("Stance of the Patient Tree","Mu","Co","35","ArM5","131","","text","He"),
        array("Retreat As Flying Vermin","Mu","Co","35","MoH","13","","text","An"),
        array("Cloak of Mist","Mu","Co","40","ArM5","131","","text","Au"),
        array("Transform to Water","Mu","Co","40","ArM5","131","","text","Aq"),
        array("Shape of the Ancient Kite","Mu","Co","40","Mutantum","HoH:TL","102","text","An"),
        array("The Lurker in the Rushes","Mu","Co","40","MoH","13","","text","An"),
        array("A Punishment for Brigands","Mu","Co","40","MoH","13","","text","An"),
        array("Silent Vigil The","Mu","Co","45","ArM5","132","","text","Te"),
        array("A Source of Tremendous Pride","Mu","Co","45","MoH","13","","text","An"),
        array("Mists of Change","Mu","Co","60","Ritual","ArM5","132","text","An"),
        array("Pass the Unyielding Portal","Mu","He","5","ArM5","137","","text",""),
        array("Piercing Shaft of Wood","Mu","Re","10","ArM5","137","","text","He"),
        array("Transformation of the Thorny Staff","Mu","He","10","ArM5","137","","text",""),
        array("Rope of Bronze","Mu","He","15","ArM5","137","","text","Te"),
        array("Aegis of Unbreakable Wood","Mu","He","15","HoH:S","36","","text",""),
        array("Thaumaturgical Transformation of Plants to Iron","Mu","He","20","ArM5","137","","text","Te"),
        array("Prune Plant","Mu","He","20","MoH","39","","text","Me"),
        array("Stir the Slumbering Tree","Mu","He","25","ArM5","137","","text","Me"),
        array("Gigantic Growth","Mu","He","25","MoH","39","","text",""),
        array("Razor Thorns","Mu","He","25","MoH","39","","text","Te"),
        array("How God Created Them","Mu","He","25","MoH","124","","text","An"),
        array("Blades of Grass Leaves of Cutting","Mu","He","30","MoH","39","","text",""),
        array("Bag of Feathers","Mu","He","35","MoH","13","","text","An"),
        array("Locked Storehouse","Mu","He","45","Ritual","Faerie Magic","MoH","65","Te"),
        array("Awaken Consciousness of Plant","Mu","He","55","Ritual","MoH","39","text","Me"),
        array("Curse of the Haunted Forest","Mu","Pe","60","Ritual","ArM5","137","text","He"),
        array("Many-Hued Conflagration The","Mu","Ig","5","ArM5","141","","text",""),
        array("Hornet Fire","Mu","Re","10","ArM5","141","","text","Ig"),
        array("Show of the Flames and Smoke","Mu","Ig","10","ArM5","141","","text",""),
        array("Enduring Flame","Mu","Ig","10","MoH","111","","text",""),
        array("Boreal Flames","Mu","Pe","15","MoH","111","","text","Ig"),
        array("Prison of Flames","Mu","Ig","20","ArM5","142","","text",""),
        array("Trapping the Fire","Mu","Ig","25","ArM5","142","","text","Te"),
        array("Let the Fire Sing You to Sleep","Mu","Ig","25","MoH","139","","text","Im"),
        array("Touch of the Realm Bound Reveler","Mu","Ig","25","RoP:M","27","Magic Realm Magic","text",""),
        array("Conflagratious Lanyard","Mu","Ig","30","MoH","13","","text","An"),
        array("Summer\'s Blessing","Mu","Ig","30","MoH","124","","text","Te"),
        array("Flames of Sculpted Ice","Mu","Ig","35","ArM5","142","","text","Aq"),
        array("The Clandestine Mask","Mu","Im","4","HoH:S","98","","text",""),
        array("Faerie Flute","Mu","Im","4","MoH","125","","text",""),
        array("Taste of the Spices and Herbs","Mu","Im","5","ArM5","145","","text",""),
        array("A Visible demand for Repair","Mu","Im","5","HoH:S","65","","text",""),
        array("The False Dune","Mu","Im","5","MoH","14","","text",""),
        array("Voice of the Leucrotta","Mu","Im","5","MoH","91","","text",""),
        array("Confound the Rival Singer","Mu","Im","5","MoH","140","","text",""),
        array("Aura of Ennobled Presence","Mu","Im","10","ArM5","145","","text",""),
        array("Notes of a Delightful Sound","Mu","Im","10","ArM5","145","","text",""),
        array("Aura of Beguiling Appearance","Mu","Im","10","HoH:S","96","","text",""),
        array("Aura of Childlike Innocence","Mu","Im","10","HoH:S","96","","text",""),
        array("Comeliness of the Crone","Mu","Im","10","MoH","22","","text",""),
        array("Aura of Childlike Innocence","Mu","Im","10","MoH","91","","text",""),
        array("Disguise of the Transformed Image","Mu","Im","15","ArM5","146","","text",""),
        array("Sight of the Warm Surface","Mu","Im","15","HoH:S","65","","text",""),
        array("The Petrine Deception","Mu","Im","15","MoH","14","","text",""),
        array("Living Fire","Mu","Im","15","MoH","125","Faerie Magic","text",""),
        array("Aura of the Simple Bard","Mu","Im","15","MoH","125","","text",""),
        array("Image Phantom","Mu","Im","20","ArM5","146","","text",""),
        array("Ball of Abysmal Music","Mu","Im","20","HoH:MC","101","Glamour Magic","text","Vi"),
        array("Glowing Footprints of the Thief","Mu","Im","20","HoH:S","65","","text",""),
        array("Safe Haven","Mu","Im","20","MoH","125","","text",""),
        array("Ogre\'s Stench","Mu","Im","30","MoH","125","","text",""),
        array("Blessing the Merchant\'s Lineage","Mu","Im","35","MoH","125","Ritual Faerie Magic","text",""),
        array("Servant of Fire","Mu","Im","35","MoH","125","Faerie Magic","text","Ig Me"),
        array("Recollection of Memories Never Quite Lived","Mu","Me","4","ArM5","149","","text",""),
        array("Recollection of Memorites Never Quite Lived","Mu","Me","4","MoH","102","Hermetic Numerology","text",""),
        array("Distraction of the Magpie","Mu","Me","10","A&A","33","","text",""),
        array("Lost in the Memory","Mu","Me","15","A&A","33","","text",""),
        array("Seed of Betrayal","Mu","Me","15","GotF","73","","text",""),
        array("Clarion Call of the War Horse","Mu","Me","15","HoH:MC","29","Sensory Magic","text",""),
        array("Enchantment of the Pedestrian Pigeon","Mu","Me","15","HoH:S","98","","text",""),
        array("Avoiding the Blame","Mu","Me","15","MoH","12","","text",""),
        array("Generous Patron the","Mu","Me","15","MoH","126","","text",""),
        array("My Old and Dear Friend","Mu","Me","20","MoH","92","","text",""),
        array("Lucid Dreamer The","Mu","In","20","TMRE","104","Dream Magic","text","Me"),
        array("The Unbidden Task","Mu","Me","25","HoH:S","70","","text",""),
        array("Mind of the Beast","Mu","Me","30","ArM5","149","","text","An"),
        array("False Prophecy","Mu","Me","30","HoH:TL","140","","text",""),
        array("Apollo\'s Fearful Gaze","Mu","Me","30","MoH","30","","text",""),
        array("Blissful Messenger","Mu","Me","30","MoH","65","Ritual Faerie Magic","text",""),
        array("Path to Lemnos The","Mu","In","30","TMRE","104","Dream Magic","text","Me"),
        array("Past of Another","Mu","Me","35","ArM5","149","Ritual","text",""),
        array("Donning the Mask of Another","Mu","Me","35","HoH:S","97","Ritual","text",""),
        array("Visions of Olympus","Mu","Me","35","RoP:M","27","Magic Realm Magic ","text",""),
        array("Inmost Companion","Mu","Me","40","ArM5","149","","text","An"),
        array("Vision of the Haunting Spirits","Mu","Me","40","ArM5","150","","text","Im"),
        array("Swords of Silver and Moonlight","Mu","Me","40","HoH:TL","140","","text","Te"),
        array("Family Gathering","Mu","In","40","Faerie Magic","MoH","67","text","Me"),
        array("Road to Lemnos The","Mu","In","40","Dream Magic","TMRE","104","text","Me"),
        array("Spectral Quinreme","Mu","Me","50","HoH:TL","140","","text","He"),
        array("Nordic Triumph","Mu","Me","65","Ritual","L&tL","122","text","He Te"),
        array("Arming the Legion of the Dead","Mu","Me","70","Ritual","HoH:TL","140","text","Te"),
        array("Crystal Dart The","Mu","Re","10","ArM5","154","","text","Te"),
        array("Supple Iron and Rigid Rope","Mu","Te","10","ArM5","154","","text",""),
        array("A Window of Singular Direction","Mu","Te","10","HoH:TL","141","","text",""),
        array("Blunting the Iron\'s Bite","Mu","Te","10","MoH","50","","text",""),
        array("Object of Increased Size","Mu","Te","15","ArM5","154","","text",""),
        array("Rock of Viscid Clay","Mu","Te","15","ArM5","154","","text",""),
        array("Conjure the Ocean\'s Breath","Mu","Te","15","MoH","31","","text",""),
        array("Hiding the Mystic Key","Mu","Te","15","TMRE","116","","text","He"),
        array("Earth that Breaks No More","Mu","Te","20","ArM5","154","","text",""),
        array("Edge of the Razor","Mu","Te","20","ArM5","154","","text",""),
        array("Ink of Noblest Metals","Mu","Te","20","Covs","97","","text","Aq"),
        array("Armatura Vitrea","Mu","Te","20","MoH","31","","text",""),
        array("The Weightless Menhir","Mu","Te","20","ToME","12","","text",""),
        array("Hardness of Adamantine","Mu","Te","25","HoH:S","37","","text",""),
        array("Short Stepof the Ghost","Mu","Te","25","MoH","93","","text","Au"),
        array("Scattering Like Light","Mu","Te","30","HoH:S","63","","text","Im"),
        array("Rapid Excavations","Mu","Te","30","MoH","14","","text","Aq"),
        array("Teeth of the Earth Mother","Mu","Te","35","ArM5","154","","text",""),
        array("Transmutation of Fire","Mu","Te","40","MoH","113","","text","He Ig"),
        array("Clear Breath of the Consumate Liar","Mu","Vi","20","GotF","73","","text","Me"),
        array("Harnessing the Essential Power (Form)","Mu","Vi","0","AncMag","67","Grigori Magic","text",""),
        array("Mirror of Opposition (Form)","Mu","Vi","0","ArM5","159","","text",""),
        array("Shroud Magic","Mu","Vi","0","ArM5","159","","text",""),
        array("Sorcerer\’s Fork The","Mu","Vi","0","ArM5","159","","text",""),
        array("Wizard\’s Boost (Form)","Mu","Vi","0","ArM5","160","","text",""),
        array("Wizard\’s Communion","Mu","Vi","0","ArM5","160","","text",""),
        array("Wizard\’s Reach (Form)","Mu","Vi","0","ArM5","160","","text",""),
        array("Facilitate the Stifled (Form) Spell","Mu","Vi","0","HoH:MC","36","","text",""),
        array("Group Wizard\’s Boost (Form)","Mu","Vi","0","MoH","113","","text",""),
        array("Wizard\'s Expansion (Form)","Mu","Vi","0","MoH","113","","text",""),
        array("Early Punishment For the Sinful Witch","Mu","Vi","0","RoP:TI","122","","text","Ig"),
        array("Wicked Jar The","Mu","Vi","0","RoP:TI","122","","text",""),
        array("Name of Power (X)","Mu","Vi","0","TMRE","76","Names of Power","text",""),
        array("Lasting Synthemata of (X) The","Mu","Vi","0","TMRE","86","Hermetic Synthemata","text",""),
        array("Synthemata of (X)","Mu","Vi","0","TMRE","86","Hermetic Synthemata","text",""),
        array("The Hedge Lord\'s Synthemata of (X)","Mu","Vi","0","TMRE","88","Synthemata Magia","text",""),
        array("Creating an Empty Book From a Filled One","Pe","An","3","Covs","97","","text",""),
        array("The Unraveled Seam","Pe","An","5","MoH","56","","text","He"),
        array("Decay Fur and Hide","Pe","An","10","ArM5","119","","text",""),
        array("Unmake This Cloth","Pe","An","10","MoH","99","","text","He"),
        array("Tire the Bounding Stag","Pe","An","10","ToME","13","","text",""),
        array("Agony of the Beast","Pe","An","15","ArM5","119","","text",""),
        array("The Unraveled Clothes","Pe","An","15","MoH","56","","text","He"),
        array("Blunt the Viper\’s Fangs","Pe","An","20","ArM5","119","","text",""),
        array("Revenge of the Bitten Toad","Pe","An","20","HoH:MC","29","Sensory Magic","text",""),
        array("Tire the Strident Destrier","Pe","An","20","ToME","13","","text",""),
        array("Falcon\’s Hood The","Pe","An","25","ArM5","119","","text",""),
        array("Cripple the Howling Wolf","Pe","An","25","ArM5","120","","text",""),
        array("Weightless Transportation of Books The","Pe","An","25","Covs","100","","text",""),
        array("Swift Knives Invisible","Pe","Re","40","Covs","96","","text","An"),
        array("Hunter\'s Lethal Arrow","Pe","An","40","HoH:TL","102","Mutantum","text",""),
        array("Comfort of the Drenched Traveler","Pe","Aq","5","ArM5","123","","text",""),
        array("Patch of Drought","Pe","Aq","10","MoH","65","","text",""),
        array("Parching Wind","Pe","Aq","20","ArM5","123","","text",""),
        array("Closing the Earth\’s Gate","Pe","Aq","25","ArM5","123","","text",""),
        array("Curse of the Desert","Pe","Aq","25","ArM5","123","","text",""),
        array("Calling the Odious Drought","Pe","Aq","50","ArM5","123","Ritual","text","Au"),
        array("Room of Stale Air","Pe","Au","15","ArM5","128","","text",""),
        array("Quiet the Raging Winds","Pe","Au","20","ArM5","128","","text",""),
        array("Be Rid of the Tell Tale Smoke","Pe","Au","20","MoH","28","","text",""),
        array("Cloudless Sky Returned The","Pe","Au","45","ArM5","128","","text",""),
        array("Touch of the Goose Feather","Pe","Co","5","ArM5","132","","text",""),
        array("Black Anne\'s Kiss","Pe","Co","10","AncMag","56","Fertility Magic","text",""),
        array("Chastise the Unrulty Anagonist","Pe","Co","10","MoH","131","","text",""),
        array("When Fortuna Blinks","Pe","Co","10","RoP:M","28","Magic Realm Magic","text",""),
        array("Dust to Dust","Pe","Co","15","ArM5","132","","text",""),
        array("Wound that Weeps The","Pe","Co","15","ArM5","133","","text",""),
        array("Invocation of Weariness","Pe","Co","20","ArM5","133","","text",""),
        array("Inner Darkness Unleashed","Pe","Co","20","MoH","132","","text",""),
        array("Blind the Insurgent Pack","Pe","Co","20","MoH","132","","text",""),
        array("Trap for the Thief in the Night","Pe","In","25","AncMag","45","Ritual Defixio Magic","text","Co"),
        array("Bane of the Decrepit Body","Pe","Co","25","ArM5","133","","text",""),
        array("Curse of the Leprous Flesh","Pe","Co","25","ArM5","133","","text",""),
        array("Grip of the Choking Hand","Pe","Co","25","ArM5","133","","text",""),
        array("Invocation of the Giant\'s Weariness","Pe","Co","25","ToME","13","","text",""),
        array("The Wound that Wails","Pe","Co","25","ToME","13","","text",""),
        array("Incantation of the Milky Eyes","Pe","Co","30","ArM5","133","","text",""),
        array("Twist of the Tongue","Pe","Co","30","ArM5","133","","text",""),
        array("Evisceration of a Thousand Knives","Pe","Co","30","GotF","60","","text",""),
        array("Slay the Innoccent","Pe","Co","30","SemE","37","","text","An"),
        array("Repose of the Eternal Moment","Pe","Co","35","RoP:M","28","Ritual Magic Realm Magic","text",""),
        array("Clenching Grasp of the Crushed Heart","Pe","Co","40","ArM5","133","","text",""),
        array("Kiss of Death The","Pe","Co","45","ArM5","133","","text",""),
        array("Curse of the Unportended Plague","Pe","Co","55","ArM5","133","Ritual","text",""),
        array("Curse of the Rotted Wood","Pe","He","5","ArM5","137","","text",""),
        array("Wizard\’s Autumn","Pe","He","15","ArM5","137","","text",""),
        array("Tree Falling in the Forest","Pe","Re","15","HoH:S","36","","text","He"),
        array("Plant\’s Withering Bane","Pe","He","20","ArM5","137","","text",""),
        array("A Spell to Kill Weeds","Pe","He","20","Covs","51","","text",""),
        array("Great Rot The","Pe","He","25","ArM5","138","","text",""),
        array("Treading the Ashen Path","Pe","He","30","ArM5","138","","text",""),
        array("Wilt","Pe","He","35","MoH","39","","text",""),
        array("A Time For Slumber","Pe","Ig","5","MoH","14","","text",""),
        array("Gloom of Evening","Pe","Ig","10","ArM5","142","","text",""),
        array("Winter\’s Icy Touch","Pe","Ig","10","ArM5","142","","text",""),
        array("Let the Sun Not Bother Me This Day","Pe","Ig","10","MoH","140","","text",""),
        array("A Place of Recuperation","Pe","Ig","15","MoH","14","","text",""),
        array("Banishment of Warmth","Pe","Ig","15","MoH","132","","text",""),
        array("Extinguish the Abhorent Flame","Pe","Ig","15","MoH","132","","text",""),
        array("Soothe the Raging Flames","Pe","Ig","20","ArM5","142","","text",""),
        array("Quench the Raging Conflagration","Pe","Ig","20","HoH:S","37","","text",""),
        array("Frosted Timber","Pe","Ig","20","MoH","40","","text",""),
        array("Cloak of Darkness","Pe","Ig","20","MoH","133","","text",""),
        array("Orb of Darkness","Pe","Ig","20","MoH","133","","text",""),
        array("Conjuration of the Indubitable Cold","Pe","Ig","25","ArM5","142","","text",""),
        array("Well Without Light","Pe","Ig","25","ArM5","142","","text",""),
        array("Abyssal touch","Pe","Ig","25","MoH","133","","text",""),
        array("Wizard\’s Icy Grip","Pe","Ig","30","ArM5","142","","text",""),
        array("Wizard\’s Eclipse","Pe","Ig","35","ArM5","142","Ritual","text",""),
        array("Domain of Darkness","Pe","Ig","45","MoH","133","","text",""),
        array("Taste of the Dulled Tongue","Pe","Im","5","ArM5","146","","text",""),
        array("Illusion of Cool Flames","Pe","Im","10","ArM5","146","","text",""),
        array("Hiding in the Crowd","Pe","Im","10","HoH:S","64","","text",""),
        array("Invisibility of the Standing Wizard","Pe","Im","15","ArM5","146","","text",""),
        array("Chamber of Muffled Passing","Pe","Im","15","MoH","133","","text",""),
        array("Removal of the Conspicuous Sigil","Pe","Im","20","ArM5","146","","text",""),
        array("Silence of the Smothered Sound","Pe","Im","20","ArM5","146","","text",""),
        array("Veil of Invisibility","Pe","Im","20","ArM5","146","","text",""),
        array("Ambush on the Deserted Road","Pe","Im","20","HoH:S","64","","text",""),
        array("Ears of a Grateful Father","Pe","Im","20","MoH","22","","text",""),
        array("Chamber of Invisibility","Pe","Im","25","ArM5","146","","text",""),
        array("Hiding the Ill Bred Bard","Pe","Im","25","MoH","125","Listed in book as lvl 15","text",""),
        array("Invisible Arms","Pe","Cr","25","MoH","125","","text","Im"),
        array("Dispel the Phantom Image","Pe","Im","0","ArM5","146","","text",""),
        array("Tip of the Tongue","Pe","Me","5","ArM5","150","","text",""),
        array("Blinded Sentry The","Pe","Me","5","GotF","73","","text",""),
        array("I Was Never Here","Pe","Me","5","MoH","93","","text",""),
        array("Trust of Childlike Faith","Pe","Me","10","ArM5","150","","text",""),
        array("Breaking the Captains\' Baton","Pe","Me","10","MoH","50","","text",""),
        array("Calm the Motion of the Heart","Pe","Me","15","ArM5","150","","text",""),
        array("Enchantment of Detachment","Pe","Me","15","ArM5","150","","text",""),
        array("Loss of But a Moment\’s Memory","Pe","Me","15","ArM5","151","","text",""),
        array("The Twice Gifted Coin","Pe","Me","15","Covs","62","","text",""),
        array("Dissolving the Wall of Shields","Pe","Me","20","HoH:S","70","","text",""),
        array("Calm Mind of Resolute Behavior","Pe","Me","20","MoH","67","","text",""),
        array("Blessing of Childlike Bliss","Pe","Me","25","ArM5","151","","text",""),
        array("Passion\’s Lost Feeling","Pe","Me","25","ArM5","151","","text",""),
        array("The Stultified Peasant","Pe","Me","30","A&A","33","","text",""),
        array("The Ever Watchful Turb","Pe","Me","35","A&A","34","","text",""),
        array("Embrace of Boethius","Pe","Me","35","HoH:MC","119","Ritual","text","CoVi"),
        array("Stolen Moments","Pe","Me","35","MoH","126","","text",""),
        array("Black Whisper","Pe","Me","40","ArM5","151","","text",""),
        array("Closed Mouth of the Nightwalker","Pe","Me","40","HoH:MC","29","Sensory Magic","text",""),
        array("Blindness of Involuntary Obstinacy","Pe","Me","40","MoH","67","","text",""),
        array("Mind Cleansed of Treachery","Pe","Me","45","MoH","67","Faerie Magic","text",""),
        array("The Clean Slate","Pe","Me","50","A&A","34","","text",""),
        array("Poisoning the Will","Pe","Me","60","ArM5","151","Ritual","text",""),
        array("Lay to Rest the Haunting Spirit","Pe","Me","Gen","ArM5","150","","text",""),
        array("Fist of Shattering","Pe","Te","10","ArM5","155","","text",""),
        array("Rusted Decay of Ten-Score Years","Pe","Te","10","ArM5","155","","text",""),
        array("Saving the Apprentice\'s Time","Pe","Te","10","MoH","31","","text",""),
        array("Pit of the Gaping Earth","Pe","Te","15","ArM5","155","","text",""),
        array("Undoing the Stonemason\'s Handiwork","Pe","Te","15","HoH:S","37","","text",""),
        array("Obliteration of the Metallic Barrier","Pe","Re","20","ArM5","155","","text","Te"),
        array("Stone to Falling Dust","Pe","Te","20","ArM5","155","","text",""),
        array("Carve Domain","Pe","Te","20","MoH","31","","text",""),
        array("Obliteration of the Traveler\'s Barrier","Pe","Te","20","SemE","37","Faerie Magic","text","He"),
        array("End of the Mighty Castle","Pe","Te","25","ArM5","155","","text",""),
        array("Gleam of the Freshly Polished Glass","Pe","Te","25","Covs","122","","text",""),
        array("Flaws of the Weaponsmith","Pe","Te","25","GotF","60","","text",""),
        array("Hauberk of Sublime Lightness","Pe","Te","30","HoH:S","38","","text",""),
        array("Cascade of Rocks","Pe","Te","40","ArM5","155","","text",""),
        array("Chastise the Unruly Fiend","Pe","Vi","10","MoH","133","","text",""),
        array("Lash of the Chastened Servant","Pe","Vi","15","RoP:TI","122","","text",""),
        array("Belittle the Ferocious Warlock","Pe","Vi","20","MoH","134","","text",""),
        array("Demon\’s Eternal Oblivion","Pe","Vi","Gen","ArM5","160","","text",""),
        array("Disenchant","Pe","Vi","Gen","ArM5","160","Ritual","text",""),
        array("Masking the Odor of Magic","Pe","Vi","Gen","ArM5","160","","text",""),
        array("Unravelling the Fabric of (Form)","Pe","Vi","Gen","ArM5","161","","text",""),
        array("Wind of Mundane Silence","Pe","Vi","Gen","ArM5","161","","text",""),
        array("Heathen Witch Reborn The","Pe","Vi","Gen","GotF","60","","text",""),
        array("Shattering the Malicious Rune","Pe","Vi","Gen","GotF","60","","text",""),
        array("Dreadful Bane of the Fae","Pe","Vi","Gen","GotF/ToME","60/14","","text",""),
        array("Sap the Griffin\'s Strength/ Dragon\'s Eternal Oblivion","Pe","Vi","Gen","GotF/ToME","60/14","","text",""),
        array("Rooster\'s Crow The","Pe","Vi","Gen","HoH:MC","29","Sensory Magic","text",""),
        array("The Heathen  Witch Reborn","Pe","Vi","Gen","HoH:S","129","","text",""),
        array("Circle of Clarity","Pe","Vi","Gen","HoH:TL","75","","text",""),
        array("Cutting the Cords","Pe","Vi","Gen","HoH:TL","75","Ritual","text",""),
        array("Stripping the Superfluous Realities","Pe","Vi","Gen","RoP:M","14","Ritual","text",""),
        array("Bind the Devil\'s Hands","Pe","Vi","Gen","RoP:TI","122","","text",""),
        array("Exorcise the Filthy Spirit","Pe","Vi","Gen","RoP:TI","122","","text",""),
        array("Avaraciousness of the Ptolemies The","Re","An","4","Covs","100","","text",""),
        array("The Wizard\'s Spindle","Re","An","4","MoH","57","","text",""),
        array("Securing the Harvest","Re","An","4","MoH","75","","text",""),
        array("Circle of Beast Warding","Re","An","5","ArM5","120","","text",""),
        array("Disguise of the Putrid Aroma","Re","An","5","ArM5","120","","text",""),
        array("Binding the Mundane Codex","Re","An","5","Covs","97","","text","Optional"),
        array("Bind Fast","Re","An","5","MoH","100","","text","He"),
        array("Th e Even Hand of the Determined Weaver","Re","Cr","5","MoH","100","","text","An"),
        array("The Treacherous Cloak","Re","An","5","MoH","100","","text",""),
        array("The Weaver\'s Subtle Art","Re","An","5","MoH","101","","text",""),
        array("Soothe the Ferocious Bear","Re","An","10","ArM5","120","","text",""),
        array("Hide to Parchment","Re","An","10","Covs","96","","text",""),
        array("A Simple Charm for the Recovery of Misfiled Books","Re","An","10","Covs","100","","text",""),
        array("Reorder the Contents of the Armarius","Re","In","10","Covs","100","","text","An"),
        array("A Days Worth of Spinning","Re","An","10","MoH","100","","text",""),
        array("A Day\'s Worth of Weaving","Re","An","10","MoH","100","","text",""),
        array("Panic of the Elephant\’s Mouse","Re","An","15","ArM5","120","","text",""),
        array("Viper\’s Gaze","Re","An","15","ArM5","120","","text",""),
        array("A Spell to Milk Cattle","Re","An","15","Covs","51","","text",""),
        array("Reorder the Contents of the Armarius","Re","In","15","Covs","100","","text","An Me"),
        array("Dressing the Human Form in Wool","Re","An","15","MoH","57","","text",""),
        array("Soothing Voice of the Stableman","Re","An","15","MoH","65","","text",""),
        array("Plague of Frogs","Re","An","20","A&A","30","","text",""),
        array("The Verminous Infestation","Re","An","20","A&A","30","","text",""),
        array("Gentle Herd The","Re","An","20","Covs","51","","text",""),
        array("Binding the Hermetic Codex","Re","An","20","Covs","97","Ritual","text","Optional"),
        array("Fury of the Charging Bull","Re","An","20","HoH:S","34","","text",""),
        array("Unfaithful Favor The","Re","An","20","HoH:TL","139","","text",""),
        array("Ward Against the Faeries that Creep and Crawl","Re","An","20","MoH","57","","text",""),
        array("The Night Badger\'s Burrow","Re","An","20","RoP:M","28","Magic Realm Magic","text","Te"),
        array("Gentle Beast The","Re","An","25","ArM5","120","","text",""),
        array("Mastering the Unruly Beast","Re","An","25","ArM5","120","","text",""),
        array("Epona\'s Bane","Re","An","25","MoH","28","","text",""),
        array("Commanding the Harnessed Beast","Re","An","30","ArM5","120","","text",""),
        array("Summon the Eldritch Bond","Re","An","35","MoH","28","","text",""),
        array("Constraint of the Strangling Vestments","Re","An","35","MoH","57","","text",""),
        array("Demand of the Frustrated Scholar Soothed","Re","An","40","Covs","100","","text",""),
        array("Voice of the King","Re","An","40","MoH","38","","text",""),
        array("Ward Against the Beasts of Legend","Re","An","0","ArM5","120","","text",""),
        array("Cloak of the Duck\’s Feathers","Re","Aq","5","ArM5","124","","text",""),
        array("Break the Oncoming Wave","Re","Aq","10","ArM5","124","","text",""),
        array("Thoughts Distinctly Burned","Re","Aq","10","Covs","97","","text",""),
        array("Shackles of the Frozen Ice","Re","Aq","10","HoH:S","35","","text",""),
        array("Exactly to Scale","Re","Aq","10","HoH:TL","139","","text","Me"),
        array("Breath of Winter","Re","Aq","15","ArM5","124","","text",""),
        array("Push of the Gentle Wave","Re","Aq","15","ArM5","124","","text",""),
        array("Still the Raging Waters","Re","Aq","15","GotF","96","","text",""),
        array("Captured by Hodor\'s Shackles","Re","Aq","20","MoH","75","","text",""),
        array("Swallowed by the Mist","Re","Aq","20","MoH","75","","text",""),
        array("Bridge of Frost","Re","Aq","30","ArM5","124","","text",""),
        array("Chaos of the Angry Waves","Re","Aq","30","ArM5","124","","text",""),
        array("Parting the Waves","Re","Aq","30","ArM5","124","","text",""),
        array("Waves of Drowning and Smashing","Re","Aq","30","ArM5","124","","text",""),
        array("Ice of Drowning","Re","Aq","35","ArM5","124","","text",""),
        array("Pull of the Watery Grave","Re","Aq","35","ArM5","124","","text",""),
        array("Tower of Whirling Water","Re","Aq","35","ArM5","124","","text",""),
        array("Neptune\’s Wrath","Re","Aq","40","ArM5","125","Ritual","text",""),
        array("Ward Against Faeries of the Waters","Re","Aq","0","ArM5","124","","text",""),
        array("Wind at the Back","Re","Au","5","ArM5","128","","text",""),
        array("Ward Against Rain","Re","Au","10","ArM5","128","","text",""),
        array("Movement Within the Sirocco","Re","Au","25","MoH","12","","text",""),
        array("Ward Against the Sirocco","Re","Au","25","MoH","12","","text",""),
        array("Clouds of Thunderous Might","Re","Au","30","ArM5","128","","text",""),
        array("Gathering of the Stormy Might","Re","Au","40","ArM5","129","","text",""),
        array("Ward Against Faeries of the Air","Re","Au","0","ArM5","128","","text",""),
        array("Curse of the Unruly Tongue","Re","Co","5","ArM5","134","","text",""),
        array("Spasms of the Uncontrolled Hand","Re","Co","5","ArM5","134","","text",""),
        array("In Christ\'s Footsteps","Re","Co","5","GotF","96","","text",""),
        array("gift of the Tortured Bowels","Re","Co","10","A&A","57","","text",""),
        array("Rise of the Feathery Body","Re","Co","10","ArM5","134","","text",""),
        array("Tossing the Brawling Brute","Re","Co","10","BCoC","75","","text",""),
        array("Ward Against the Curious Scullion","Re","Co","10","Covs","104","","text",""),
        array("Sealing the Lips","Re","Co","10","MoH","58","","text",""),
        array("Follower\'s Bane","Re","Co","10","MoH","122","Faerie Magic","text",""),
        array("The Promenade of Caesar","Re","Co","15","AncMag","56","Fertility Magic","text",""),
        array("Despair of the Quivering Manacles","Re","Co","15","ArM5","134","","text",""),
        array("Endurance of the Berserkers","Re","Co","15","ArM5","134","","text",""),
        array("Gift of the Frog\’s Legs","Re","Co","15","ArM5","134","","text",""),
        array("Lifting the Dangling Puppet","Re","Co","15","ArM5","134","","text",""),
        array("Marking the Territory","ArM5","120","15","HoH:MC","29","Sensory Magic","text",""),
        array("Wizard\'s Leap","ArM5","120","15","HoH:S","36","","text",""),
        array("Retreat into the Shell of Shadow","MoH","28","15","MoH","131","","text",""),
        array("Gift of Vigor The","ArM5","120","20","ArM5","134","","text",""),
        array("Topple the Brutish Band","MoH","28","20","BCoC","75","","text",""),
        array("Tireless Flight The","MoH","57","20","HoH:TL","102","Mutantum","text",""),
        array("Stance of the Firm Buttoked Knight","Covs","100","20","L&tL","60","","text",""),
        array("Remain within these Walls","MoH","38","20","MoH","101","Hermetic Geometry","text",""),
        array("Arachne\'s Tuition","ArM5","120","20","MoH","101","","text",""),
        array("Jump of the Lynx","ArM5","124","20","MoH","124","","text",""),
        array("Protesting Adversary Held Still The","ArM5","124","20","MoH","132","","text",""),
        array("Blessed Releif of the Benighted Reins","Covs","97","25","A&A","60","","text",""),
        array("Sever the Unwanted Limb","HoH:S","35","25","A&A","60","","text",""),
        array("Awaken the Slumbering Corpse","HoH:TL","139","25","ArM5","134","","text",""),
        array("Strings of the Unwilling Marionette","ArM5","124","25","ArM5","135","","text",""),
        array("Stillness of the Dead","ArM5","124","25","MoH","84","","text","An"),
        array("Seven-League Stride","GotF","96","30","ArM5","135","","text",""),
        array("Hold Chur","MoH","75","30","MoH","22","","text",""),
        array("House Arrest of the Unruly Child","MoH","75","30","MoH","22","","text",""),
        array("It\'s Raining Men","ArM5","124","30","MoH","22","","text",""),
        array("Possess the Deceased Host","ArM5","124","30","TMRE","74","Must be a living ghost","text",""),
        array("Possess the Living Host","ArM5","124","30","TMRE","74","Must be a living ghost","text",""),
        array("Leap of Homecoming The","ArM5","124","35","ArM5","135","","text",""),
        array("Walking Corpse The","ArM5","124","35","ArM5","135","Ritual","text","Me"),
        array("Awaken the Slumbering Dead","ArM5","124","35","BCoC","74","","text",""),
        array("Seven Leagues Travel","ArM5","124","35","MoH","22","","text",""),
        array("Morphean Gate The","ArM5","125","40","TMRE","109","Greater Dream Grimore","text","Co Me"),
        array("Passage to the Place Pictured","ArM5","124","45","AncMag","45","Ritual Defixio Magic","text",""),
        array("A Useful Inculcator of Comments","ArM5","128","4","Covs","99","","text",""),
        array("Brew the Healing Tonic","ArM5","128","5","A&A","70","","text",""),
        array("Dance of the Staves","MoH","12","5","ArM5","138","","text",""),
        array("Clothier\'s Craft Done in an Instant","MoH","12","5","MoH","58","","text",""),
        array("The Mended Tear","ArM5","128","5","MoH","58","","text",""),
        array("Acorns for Amusement","ArM5","129","5","ToME","55","","text",""),
        array("Rickety Stack","ArM5","128","5","ToME","55","","text",""),
        array("Repel the Wooden Shafts","ArM5","134","10","ArM5","138","","text",""),
        array("Rough Hewn Servant","ArM5","134","10","ToME","55","","text",""),
        array("Strike of the Angered Branch","GotF","96","15","ArM5","138","","text",""),
        array("Tangle of Wood and Thorns","A&A","57","15","ArM5","138","","text",""),
        array("Drawing Up the Siege Ladder","ArM5","134","15","Covs","101","","text",""),
        array("Ring of Ever Bloom","BCoC","75","15","MoH","39","","text",""),
        array("Enemies All Aquiver","Covs","104","15","ToME","55","","text",""),
        array("Coils of the Entangling Plants","MoH","58","20","ArM5","138","","text",""),
        array("The Animate Attire","Re","He","20","MoH","58","","text",""),
        array("Embroidering the Wizard\'s Robes","Re","He","20","MoH","58","","text",""),
        array("Everlasting Music","Re","He","20","MoH","124","Spell Timing","text","An"),
        array("Mend thy Broken Strings","Re","He","20","MoH","139","","text",""),
        array("Casrved Assassin","Re","He","20","ToME","55","","text",""),
        array("Tomb of Kaineus","Re","He","20","ToME","55","","text",""),
        array("Lord of the Trees","Re","He","25","ArM5","139","","text",""),
        array("Treacherous Spear The","Re","He","25","ArM5","139","","text",""),
        array("Twist the Living Tree","Re","He","25","ArM5","139","","text",""),
        array("Ward Against Wood","Re","He","25","ArM5","139","","text",""),
        array("Mystical Carpenter The","Re","He","25","Covs","51","","text",""),
        array("Tree Top Walk","Re","He","25","MoH","39","","text",""),
        array("Controlled Growth","Re","He","25","MoH","39","Ritual","text",""),
        array("Halt the Piercing Shafts","Re","He","25","MoH","50","","text","Te"),
        array("Freeing the Striding Tree","Re","He","30","ArM5","139","","text",""),
        array("Prison Floral","Re","He","30","MoH","40","","text",""),
        array("Carnivorous House","Re","He","35","ToME","55","","text",""),
        array("Calling the Council of the Trees","Re","In","45","ArM5","139","Ritual","text","He"),
        array("Command of the Forrest","Re","He","55","MoH","40","Ritual","text","Me"),
        array("Ward Against Faeries of the Wood","Re","He","0","ArM5","138","","text",""),
        array("Tremulous Vault of the Torch\’s Flame","Re","Ig","5","ArM5","142","","text",""),
        array("Leap of the Fire","Re","Ig","10","ArM5","143","","text",""),
        array("Discourse of Glowing Tongues","Re","Ig","10","MoH","111","","text",""),
        array("Ward Against Flame","Re","Ig","15","Covs","104","","text",""),
        array("Light Shaft of the Night","Re","Ig","20","ArM5","143","","text",""),
        array("The Obedient fire","Re","Ig","20","HoH:S","37","","text",""),
        array("Command the Living Fire","Re","Ig","20","RoP:M","133","","text",""),
        array("Coerce the Spirit of Fire","Re","Ig","20","TMRE","28","","text",""),
        array("Burst of the Sweeping Flames","Re","Ig","25","ArM5","143","","text",""),
        array("Ward Against Heat and Flames","Re","Ig","25","ArM5","143","","text",""),
        array("Discriminating Flames","Re","Ig","25","MoH","112","","text",""),
        array("Petite Phoenix","Re","Ig","30","MoH","112","","text",""),
        array("Ward Against Mundane Intrusions","Re","Ig","35","Covs","104","","text","AnAq CoHe"),
        array("Ward Against Immolation","Re","Ig","35","MoH","112","","text",""),
        array("Unified Flame","Re","Ig","35","MoH","112","","text",""),
        array("Summoning the Spirit of Fire","Re","Ig","40","TMRE","29","","text",""),
        array("Circle of Undisturbed Rest","Re","Im","5","MoH","30","","text",""),
        array("Illusion of the Shifted Image","Re","Im","10","ArM5","146","","text",""),
        array("Wizard\’s Sidestep","Re","Im","10","ArM5","147","","text",""),
        array("Color Explosion","Re","Im","15","MoH","125","","text",""),
        array("Captive Voice The","Re","Im","25","ArM5","147","","text",""),
        array("Confusion of the Insane Vibrations","Re","Im","30","ArM5","147","","text",""),
        array("Image from the Wizard Torn","Re","In","30","ArM5","147","","text","Im"),
        array("Illusion of the Misplaced Castle","Re","Im","50","ArM5","147","Ritual","text",""),
        array("Restore the Moved Image","Re","Im","0","ArM5","146","","text",""),
        array("Call to Slumber The","Re","Me","10","ArM5","151","","text",""),
        array("Snap of Awakening","Re","Me","10","ArM5","151","","text",""),
        array("Confusion of the Numbed Will","Re","Me","15","ArM5","151","","text",""),
        array("Call the Dream","Re","Me","20","A&A","34","","text",""),
        array("Searching the Haystack for a Needle","Re","Me","20","A&A","34","","text",""),
        array("Singlemindedness of the Concentration Wizard","Re","Me","20","A&A","34","","text",""),
        array("Aura of Rightful Authority","Re","Me","20","ArM5","151","","text",""),
        array("Coerce the Spirits of the Night","Re","Me","20","ArM5","152","","text",""),
        array("Scent of Peaceful Slumber","Re","Me","20","ArM5","152","","text",""),
        array("Enchantment of my Lover\'s Eye","Re","Me","20","BCoC","74","","text",""),
        array("Enchantment of My Lover\'s Eye","Re","Me","20","BCoC","74","","text",""),
        array("Resolute Mind of the Tireless Researcher The","Re","Me","20","Covs","122","","text",""),
        array("Coerce the Spirit of Anger","Re","Me","20","HoH:S","99","","text",""),
        array("Trust Me","Re","Me","20","HoH:TL","73","","text",""),
        array("Sinister Road","Re","Me","20","MoH","126","","text",""),
        array("Lay Your Burdens on Me","Re","Me","20","MoH","141","","text",""),
        array("Aura of Inconsequence","Re","Me","25","HoH:TL","73","","text",""),
        array("Visions of the Infernal Terrors","Re","Me","30","ArM5","152","","text",""),
        array("Burning the Issue of the Day","Re","Me","30","HoH:S","98","","text",""),
        array("Penitent\'s Confession The","Re","Me","30","HoH:TL","73","","text",""),
        array("Raise the Siege","Re","Me","30","LoM","116","","text",""),
        array("Dancing Mania","Re","Me","30","MoH","126","","text",""),
        array("Endless Laughter","Re","Me","30","MoH","126","","text",""),
        array("The Visage of Mot","Re","Me","35","AncMag","33","Ritual Canaanite Necromancy","text",""),
        array("Call to Arms","Re","In","35","AncMag","44","Ritual Defixio Magic","text","Me Co"),
        array("Hibernation of the Slumbering Turb","Re","Cr","35","HoH:MC","29","Ritual Sensory Magic","text","Me"),
        array("Voices From Hollow Spaces","Re","Me","35","HoH:TL","140","","text",""),
        array("Slave of Charity","Re","Me","35","MoH","30","","text",""),
        array("Enslave the Mortal Mind","Re","Me","40","ArM5","152","","text",""),
        array("Incantation of Summoning the Dead","Re","Me","40","ArM5","152","Ritual","text",""),
        array("Shrouded Glen The","Re","Me","40","ArM5","152","Ritual","text",""),
        array("Summoning the Spirit of Anger","Re","Me","40","HoH:S","99","","text",""),
        array("Face in the Mirror The","Re","Me","40","HoH:TL","140","","text",""),
        array("Exchange of the Two Minds","Re","Me","55","ArM5","152","Ritual","text",""),
        array("Call the Fallen Eagles From the Mist","Re","Me","65","HoH:TL","141","Ritual","text",""),
        array("Ring of Warding Against Spirits","Re","Me","Gen","ArM5","151","","text",""),
        array("Fortification of the Memory Palace","Re","Me","Gen","TMRE","27","","text",""),
        array("Invisible Glassworker The","Re","Te","4","Covs","51","","text",""),
        array("Scribe te Perfect Circle","Re","Cr","4","MoH","102","Hermetic Numerology","text","Te"),
        array("Scribe the Perfect Circle","Re","Cr","4","TMRE","96","","text","Te"),
        array("Unseen Arm","Re","Te","5","ArM5","155","","text",""),
        array("The Wizard\'s Parry","Re","Te","5","MoH","50","","text",""),
        array("The Poet\'s Bust","Re","Te","5","A&A","133","","text",""),
        array("The Unseen Arm","Re","Te","5","MoH","102","Hermetic Numerology","text",""),
        array("Trackless Step","Re","Te","10","ArM5","155","","text",""),
        array("Wielding the Invisible Sling","Re","Te","10","ArM5","155","","text",""),
        array("Unseen Porter The","Re","Te","10","ArM5","156","","text",""),
        array("Key of Theodorus The ","Re","Te","10","C&G","10","","text",""),
        array("Invisible Sling of Vilano","Re","Te","10","HoH:S","38","","text",""),
        array("Disarm the Warrior","Re","Te","10","MoH","50","","text",""),
        array("Well Trodden Path the","Re","Te","10","MoH","141","","text",""),
        array("Grasp of the Distant Slingstone","Re","Te","10","SemE","37","","text",""),
        array("Earth\’s Carbuncle The","Re","Mu","15","ArM5","156","","text","Te"),
        array("Hands of the Grasping Earth","Re","Mu","15","ArM5","156","","text","Te"),
        array("Spell of Wrought Iron The","Re","Te","15","Covs","51","","text",""),
        array("Autodictation","Re","Te","15","Covs","96","","text",""),
        array("Scribe\'s Touch The","Re","Te","15","Covs","96","","text",""),
        array("Ominous Levitation of the Weighty Stone","Re","Te","15","HoH:S","38","","text",""),
        array("Foras Vim","Re","Te","15","MoH","31","","text",""),
        array("Tilled Soil","Re","Te","15","MoH","40","","text",""),
        array("Instant Ring Fort","Re","Te","15","MoH","50","","text",""),
        array("Gift of the Oneiropomp","Re","Mu","15","TMRE","109","Greater Dream Grimore","text","Te Me"),
        array("Crest of the Earth Wave","Re","Te","20","ArM5","156","","text",""),
        array("Forgiving Earth The","Re","Te","20","ArM5","156","","text",""),
        array("Unyielding Earth","Re","Te","20","ArM5","156","","text",""),
        array("Phantom Blacksmith The","Re","Te","20","Covs","51","","text",""),
        array("The Unerring Lance","Re","Te","20","L&tL","60","","text",""),
        array("Invisible Hand of the Theif","Re","Te","20","MoH","93","","text",""),
        array("Perfected Structure The","Re","Cr","20","TMRE","96","","text","Te He"),
        array("Perfection of the Well-Designed Chamber","Re","Cr","20","TMRE","96","","text","Te He"),
        array("Nature\'s Kindest Seat","Re","Te","25","MoH","142","","text",""),
        array("Earth Shock","Re","Te","30","ArM5","156","","text",""),
        array("Earth Split Asunder The","Re","Te","30","ArM5","156","","text",""),
        array("Ambulatory Laboratory The","Re","Te","30","Covs","122","","text",""),
        array("Mold the Earth Within Sight","Re","Te","30","MoH","40","","text",""),
        array("Circular Wall of Shields","Re","Te","30","MoH","50","","text",""),
        array("Creeping Chasm","Re","Te","35","ArM5","156","","text",""),
        array("Pitsdim\'s Downfall","Re","Te","50","BCoC","75","","text",""),
        array("Hermes\’ Portal","Re","Te","75","ArM5","156","Ritual","text",""),
        array("Ward Against Faeries of the Mountain","Re","Te","0","ArM5","155","","text",""),
        array("Gather the Essence of the Beast","Re","Vi","15","ArM5","162","","text",""),
        array("Distillation of the Purist Stream","Re","Vi","15","Covs","77","","text",""),
        array("Cleanse the Verminous Vis","Re","Vi","15","RoP:TI","122","","text",""),
        array("Swift Wings of Timeless Days","Re","Vi","20","RoP:M","28","Magic Realm Magic","text",""),
        array("Command the Vile Spirit","Re","Vi","20","RoP:TI","122","","text",""),
        array("Divide the Gathered Essence","Re","Vi","25","TMRE","40","","text",""),
        array("A Day\'s Grace","Re","Vi","30","MoH","102","Celestial Magic","text",""),
        array("Aegis of the Hearth","Re","Vi","0","ArM5","161","Ritual","text",""),
        array("Circular Ward Against Demons","Re","Vi","0","ArM5","162","","text",""),
        array("Maintaining the Demanding Spell","Re","Vi","0","ArM5","162","","text",""),
        array("Opening the Intangible Tunnel","Re","Vi","0","ArM5","162","","text",""),
        array("Suppressing the Wizard\’s Handiwork","Re","Vi","0","ArM5","162","","text",""),
        array("Watching Ward","Re","Vi","0","ArM5","162","Ritual","text",""),
        array("Invoke the Pact of Zelos","Re","Vi","0","HoH:S","100","Hermetic Theurgy","text",""),
        array("Quiet the Cursing Tounge","Re","Vi","0","HoH:S","129","","text",""),
        array("Wrappings of Metaphysical Iron","Re","Vi","0","MoH","68","","text",""),
        array("The Patient Spell","Re","Vi","0","MoH","113","","text",""),
        array("Adjuration of the Hell-Sworn Spirit","Re","Vi","0","RoP:TI","122","","text",""),
        array("Sustain a Spell of (Form)","Re","Vi","0","TMRE","27","Spell Binding","text",""),
        array("Invoke the Pact of (Daimon)","Re","Vi","0","TMRE","80","Ritual Hermetic Theurgy","text",""),
        array("Bind the Mystical Structure","Re","Vi","0","TMRE","98","Ritual Hermetic Archetecture","text",""),
        array("Tranformation of the Living Ghost","Te","Fo","0","TMRE","71","Ritual Living Ghost","text",""),
        array("Invoke the Spirit of (Spell)","Te","Fo","0","TMRE","79","Hermetic Theurgy","text",""),
        array("Invoke the Spirit of (Form)","Te","Fo","0","TMRE","80","Hermetic Theurgy","text",""),
        array("Ascendant Form of the Intendant Heirarch","Te","Fo","0","TMRE","82 -->","Ritual Ascending to the Hall of Heroes","text","")
        );
        //Print each line of the new array    
        //There is a good chance that elements in php arrays are referenced by the names defined by the initial row reading, the column names.  
        //I may have to use that column name as an explicit reference to the item I\'m looking for.
        foreach ($csvdata as $spell) {
        echo "<pre>";
        echo $spell[0];
        echo PHP_EOL;
        echo $spell[1];
        echo $spell[2];
        echo $spell[3];
        echo "; Book/Page:";
        echo $spell[4];
        echo "/";
        echo $spell[5];
        echo "; Notes: ";
        echo $spell[6];
        echo "; Requisites: ";
        echo $spell[8];
        echo PHP_EOL;
        echo $spell[7];
        echo PHP_EOL;
        echo PHP_EOL;
            }
        ?>
    </body>
</html>